services:
  real-simple-microservice:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8080:8080"
  complete-app :
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
