name: Deploy to AWS after tests pass

on:
  workflow_run:
    workflows: ["CI Pipeline on master > uni test - IT"]
    types:
      - completed

jobs:
  prepare:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      #      - name: Deploy to AWS
      #        run: |
      #          echo "Deploying to AWS..."
      #          # add your deployment commands here
      - name: Build with Maven
        run: mvn clean install

  deploy-to-aws:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          mask-aws-account-id: "no"

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-spring-app .

      - name: Push to Elastic Beanstalk
        run: |
          zip -r deploy.zip Dockerrun.aws.json
          aws s3 cp deploy.zip s3://elasticbeanstalk-eu-north-1-183619025518/simple-springboot-app/$GITHUB_SHA.zip
          aws elasticbeanstalk create-application-version \
            --application-name simple-springboot-app \
            --version-label "$GITHUB_SHA-$(date +%s)"
            --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-183619025518,S3Key=simple-springboot-app/$GITHUB_SHA.zip
          
          aws elasticbeanstalk update-environment \
            --environment-name simple-springboot-app-env \
            --version-label $GITHUB_SHA
